apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task8
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: backend
          image: task8-backend:3.0
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 5000

          env:
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: task8-config
                  key: BACKEND_PORT

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: task8-config
                  key: MONGO_HOST

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: task8-config
                  key: MONGO_PORT

            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: task8-config
                  key: MONGO_DATABASE

            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: task8
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
