apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: task8
type: Opaque
stringData:
  mongo-root-username: REPLACE_WITH_USERNAME
  mongo-root-password: REPLACE_WITH_SECURE_PASSWORD
