apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: task8
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: task8
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-sa
  namespace: task8
automountServiceAccountToken: false
